import assert from 'node:assert/strict';
import {sanitizeTexts,MAX_TEXT_LAYERS} from '../dist/model.js';
import {textStyle} from '../dist/text-render.js';
import {captionDefaults,applyCaptionPreset} from '../dist/caption-presets.js';

const [text]=sanitizeTexts([{id:'title',text:'東京\nNIGHT',font:'Serif',align:'right',weight:'800',color:'#f2c8b0',box:'dark',outline:12,size:500,x:2,y:-1,opacity:2,fadeIn:8,fadeOut:-2,motion:'rise',motionDuration:4,start:1,end:0}]);
assert.equal(text.text,'東京\nNIGHT');
assert.equal(text.weight,800);
assert.equal(text.outline,12);
assert.equal(text.size,300);
assert.equal(text.x,1);
assert.equal(text.y,0);
assert.ok(text.end>text.start);
assert.equal(textStyle(text).outline,12);
assert.equal(textStyle(text).outlineColor,'#000000');
assert.equal(textStyle(text).box,'dark');
const [spaced]=sanitizeTexts([{text:'TYPE',letterSpacing:999,lineHeight:.1}]);
assert.equal(spaced.letterSpacing,50);assert.equal(spaced.lineHeight,.6);
assert.equal(sanitizeTexts(Array.from({length:MAX_TEXT_LAYERS+5},(_,i)=>({text:String(i)}))).length,MAX_TEXT_LAYERS);
assert.equal('raster' in sanitizeTexts([{text:'safe',raster:{data:'large'}}])[0],false);
const subtitle=captionDefaults(1,4,'subtitle');assert.equal(subtitle.outline,4);assert.equal(subtitle.y,.86);assert.equal(subtitle.shadow,true);
const custom={};applyCaptionPreset(custom,'lowerThird');assert.equal(custom.align,'left');assert.equal(custom.motion,'slide-left');
assert.equal(captionDefaults(0,2,'varietyYellow').outline,7);assert.equal(captionDefaults(0,2,'varietyRed').color,'#ff4a3d');assert.equal(captionDefaults(0,2,'cornerTag').align,'left');
const tv=captionDefaults(0,2,'tvBlueRed');assert.equal(tv.outerOutline,8);assert.deepEqual(tv.lineColors,['#ffffff','#b71318']);
const impact=captionDefaults(0,2,'tvImpact');impact.accentWords='欠かせない、モノ';const impactStyle=textStyle(impact);assert.equal(impactStyle.outerOutlineColor,'#ffffff');assert.deepEqual(impactStyle.accentWords,['欠かせない','モノ']);
const [decorated]=sanitizeTexts([{text:'装飾',outline:99,outlineColor:'#123456',shadow:true,shadowOpacity:2,shadowBlur:99,shadowX:-99,shadowY:99,box:'custom',boxColor:'#abcdef',boxOpacity:.4,boxPadding:.5,boxRadius:.2,motion:'pop'}]);
assert.equal(decorated.outline,20);assert.equal(decorated.shadowOpacity,1);assert.equal(decorated.shadowBlur,40);assert.equal(decorated.shadowX,-50);assert.equal(decorated.shadowY,50);assert.equal(decorated.box,'custom');assert.equal(decorated.motion,'pop');
const [rich]=sanitizeTexts([{text:'二重フチ',lineColors:['#112233','bad'],accentWords:'重要語',accentColor:'#ff817b',outerOutline:99,outerOutlineColor:'#abcdef'}]);assert.deepEqual(rich.lineColors,['#112233','#ffffff']);assert.equal(rich.accentWords,'重要語');assert.equal(rich.outerOutline,20);assert.equal(rich.outerOutlineColor,'#abcdef');
console.log('Text layers: 120 captions, decoration, presets, validation and persisted raster exclusion PASS');
